import json

# Load one ticket
with open("incident_cases.json", "r") as f:
    tickets = json.load(f)

case = tickets[0]

# Simple SOC Incident Report Text
report = f"""
SOC INCIDENT REPORT
===================

Case ID: {case['case_id']}
Alert ID: {case['alert_id']}
Created Time: {case['created_time']}

1. Executive Summary
--------------------
A suspicious email alert was generated by the phishing/spam detection pipeline.
Tier-2 investigation classified this event as:

Verdict: {case['tier2_verdict']}

2. Severity and Priority
------------------------
Severity: {case['severity']}
Priority: {case['priority']}

3. Response Actions Taken
-------------------------
Action Executed: {case['response_action']}
Status: {case['status']}

4. Analyst Notes
----------------
{case['notes']}

5. MITRE ATT&CK Mapping (Basic)
------------------------------
Technique: T1566.001 (Phishing: Spearphishing via Email)
Category: Initial Access

6. Recommendations
------------------
- Improve keyword rules to reduce false positives
- Add URL/domain enrichment (VirusTotal)
- Integrate ticketing with SIEM tools

===================
END OF REPORT
"""

# Save report
with open("CASE-0001-report.txt", "w") as f:
    f.write(report)

print("Incident report generated: CASE-0001-report.txt")
print(report)
